### ISSUE TITLE
is this project death? should i use nose even if nose is death? is this project production usable?

### ISSUE THREAD

**Issue by abioneperhobby** [bfirsh/needle#46]
hi,

thanks for this very interesting project.

1. there is no commit since the last year and needle are in version 0.3 . is this project death?
2. the project needs nose, but nose project is death (http://nose.readthedocs.io/en/latest/) so nose propose to use node2. What should i with needle?
3. needle with nose permits to obtain good result or should i move away? any suggestion?

thanks.

**Comment by acdha** [comment]
Try using it. Not having recent commits usually means only that the current users don't need anything changed. If you look at the code, it doesn't force a dependency on nose 1.x so it will only require a change when nose2 is released if the plugin API changes.

**Comment by abioneperhobby** [comment]
Thanks
