### ISSUE TITLE
Can i commit my new feature: whitelist?

### ISSUE THREAD

**Issue by abioneperhobby** [bfirsh/needle#48]
hi,

sometime i needed to remove something inside my screenshot div because sometime some changes can be considered normal.

e.g. i have a dashboard with some graphs, i need to make a visual comparison of the dashboard but changes in graph can be normal.

so i updated the library and now assertScreenshot can take a whitelist of css selector as parameters.

can i commit my update?

thanks

**Comment by jphalip** [comment]
Thanks for the suggestion. There's no need to open a separate ticket, so I'm going to close this one. I've left some comments in the PR #49.
