### ISSUE TITLE
Support for Selenium 3

### ISSUE THREAD

**Issue by sterago** [bfirsh/needle#55]
`setup.py` defines a requirement for `selenium <3`
Are there any plans to remove this restriction?

**Comment by jphalip** [comment]
I see no reason for keeping this restriction. However, first one needs to check that needle's code is compatible or to provide the required code updates to make it compatible both with Selenium 2 & 3. Have you tested it with Selenium 3 yet?

**Comment by sterago** [comment]
Yes, I did some basic tests using a fresh virtualenv with `needle==0.3` and `selenium==3.0.1` and I didn't see any problems

**Comment by jphalip** [comment]
Ok thanks. Could you submit a pull request with changes to ``setup.py`` and ``.travis.yml`` so we can check that all tests pass?

**Comment by sterago** [comment]
sure thing

**Comment by jphalip** [comment]
Fixed in #56

**Comment by benpatterson** [comment]
We are also impacted by the `<3` requirement; thank you for the fix! 

I'm wondering if the changes will be bundled and released soon? Willing to put in a cycle to make that happen if you are short on time... Cheers.

**Comment by jphalip** [comment]
@benpatterson Thanks for the reminder, I've just pushed a new release.

**Comment by benpatterson** [comment]
Awesome; thank you @jphalip !
