### ISSUE TITLE
Fix tests for Python 2.6 / or drop Python 2.6

### ISSUE THREAD

**Issue by jphalip** [bfirsh/needle#59]
The tests are currently failing on Travis since the recent release of Pillow 4.0.0, which is dropping Python 2.6 support: http://pillow.readthedocs.io/en/stable/releasenotes/4.0.0.html#python-2-6-and-3-2-dropped

We should either fix our test matrix, or drop Python 2.6 support ourselves too as it's not official supported by the core Python team any more.

**Comment by acdha** [comment]
👍  for simply dropping support following the rationale in http://www.curiousefficiency.org/posts/2015/04/stop-supporting-python26.html

**Comment by jphalip** [comment]
Agreed. I'll try to fix the tests for now, but we should plan to remove 2.6 support in the 5.0 release.

**Comment by jphalip** [comment]
Ok, removed 2.6 from the test matrix
