### ISSUE TITLE
Add Firefox to the Travis test matrix

### ISSUE THREAD

**Issue by jphalip** [bfirsh/needle#60]
Currently we only test with PhantomJS. For more completeness, it'd be useful to add Firefox following the steps here: https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

**Comment by cgoldberg** [comment]
+1 for adding Chrome also

**Comment by jmbowman** [comment]
Since both Chrome and Firefox have been added to Travis, I presume this can be closed now.

**Comment by jphalip** [comment]
That's right, thanks.
